{
 "title": "Loan Approval System MLOps Dashboard",
 "tags": [
  "mlops",
  "loan-approval",
  "fastapi"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total API Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(loan_requests_total)", "legendFormat": "Total Requests" }
   ]
  },
  {
   "title": "Total Approved Loans",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(loan_predictions_total{decision=\"Approved\"})",
     "legendFormat": "Approved"
    }
   ]
  },
  {
   "title": "Total Rejected Loans",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(loan_predictions_total{decision=\"Rejected\"})",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Approval Rate (%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(loan_predictions_total{decision=\"Approved\"}) / sum(loan_predictions_total) * 100",
     "legendFormat": "Approval Rate"
    }
   ]
  },
  {
   "title": "Request Latency (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "rate(loan_request_latency_seconds_sum[5m]) / rate(loan_request_latency_seconds_count[5m])",
     "legendFormat": "Avg Latency"
    }
   ]
  },
  {
   "title": "Prediction Decision Breakdown Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum by (decision) (rate(loan_predictions_total[5m]))",
     "legendFormat": "{{decision}}"
    }
   ]
  }
 ]
}