global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'loan-approval-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:8000', 'loan-approval-api-service:8000']
