apiVersion: v1
kind: Service
metadata:
  name: loan-approval-api-service
  namespace: default
  labels:
    app: loan-approval-api
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
      name: http
  selector:
    app: loan-approval-api
